services:
  db-social:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - social-vol:/usr/local/pgsql/data

volumes:
  social-vol:
    external: true